version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: client/Dockerfile
    image: mishaelr/yolomy:1.0
    container_name: containerfront
    ports:
      - '3000:3000'
    env_file:
      - './.env'
    networks:
      - mongo_net
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: mishaelr/yolomy:1.0
    container_name: mongo-express-app
    ports:
      - '5000:5000'
    env_file:
      - './.env'
    networks:
      - mongo_net
    depends_on:
      - mongo  

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    env_file:
      - './.env'
    volumes:
      - database:/data/db
    networks:
      - mongo_net
volumes:
    database:
networks:
  mongo_net:
    driver: bridge