version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: mishaelr/yolomy
    container_name: mongo-express-app
    ports:
      - '8000:8000'
    env_file:
      - './.env'
    networks:
      - mongo_net
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: mish
      MONGO_INITDB_ROOT_PASSWORD: Access
    volumes:
      - database:/data/db
    networks:
      - mongo_net
volumes:
  database:

networks:
  your_network:
    driver: bridge